### ISSUE TITLE
MySQL 数据库密码泄露，可登录数据库

### ISSUE THREAD

**Issue by wuhan005** [egotong/nows#16]
`data.php`泄露了数据库用户名密码，使得可登录数据库。

请及时修改数据库密码。

**Comment by luoyou** [comment]
好奇看了一眼, 貌似看到很多不好的东西..... 

建议把内容里面的工具隐掉, 不然会让更多人知道登录方法的.

**Comment by wuhan005** [comment]
嗯 已修改

**Comment by chenxuuu** [comment]
兄啊，git可以看到历史版本的，不是简单push一个commit改文件啊😂

**Comment by wuhan005** [comment]
是啊。。。应该直接改生产环境数据库的密码。。。 @egotong

**Comment by wenbochang888** [comment]
@chenxuuu 那这种情况，怎么清楚git得提交记录呢？求教

**Comment by chenxuuu** [comment]
@wenbochang888 像这个仓库没几个commit，本地新建个repo强推（-force参数，或者TortoiseGit上面的unknow选项）上来就好了，历史版本要不要无所谓

如果历史版本不想删，那就本地改历史记录，改完再强推到GitHub

**Comment by majorworld** [comment]
> 好奇看了一眼, 貌似看到很多不好的东西.....
> 
> 建议把内容里面的工具隐掉, 不然会让更多人知道登录方法的.

我特别想知道很多不好的东西是什么，哈哈。
